# Generated by Django 5.0.7 on 2024-07-31 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisements',
            fields=[
                ('advertisement_id', models.AutoField(editable=False, primary_key=True, serialize=False, unique=True)),
                ('advertisement_name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('advertisement_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='dxvllogs',
            options={'ordering': ['advertisement', 'date_aired'], 'verbose_name': 'DXVL Log'},
        ),
    ]
