# Generated by Django 5.0.7 on 2024-07-21 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_dxvllogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxvllogs',
            name='date_aired',
            field=models.DateTimeField(),
        ),
    ]
