# Generated by Django 5.0.7 on 2024-07-30 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_advertisements'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisements',
            name='advertisement_id',
            field=models.AutoField(editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
