# Generated by Django 5.0.7 on 2024-07-22 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_dxvllogs_date_aired'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXVLLogNames',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'db_table': 'dxvl_log_filenames',
            },
        ),
    ]
