# Generated by Django 5.0.7 on 2024-07-22 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_dxvllognames_file_state'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dxvllognames',
            options={'verbose_name': 'DXVL Log File Name'},
        ),
        migrations.AddField(
            model_name='dxvllognames',
            name='file_lines',
            field=models.IntegerField(default=0),
        ),
    ]
