# Generated by Django 5.0.7 on 2024-07-22 04:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_dxvllognames_options_dxvllognames_file_lines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxvllogs',
            name='added_by',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
