# Generated by Django 5.0.7 on 2024-07-22 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_alter_dxvllogs_added_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxvllogs',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
