# Generated by Django 5.0.7 on 2024-07-22 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_dxvllogs_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='DXVLAdvertisementPrices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('advertisement', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'DXVL Advertisement Price',
                'db_table': 'dxvl_advertisement_prices',
            },
        ),
    ]
