# Generated by Django 5.0.7 on 2024-07-22 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dxvladvertisementprices'),
    ]

    operations = [
        migrations.AddField(
            model_name='dxvllogs',
            name='remarks',
            field=models.BooleanField(default=True),
        ),
    ]
