# Generated by Django 5.0.7 on 2024-07-23 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_dxvllogs_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dxvlusers',
            name='user_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dxvlusers',
            name='user_mobile_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
